---

- platform: template
  switches:
    shabbat_mode:
      friendly_name: "מצב שבת"
      unique_id: 6ec56ed5-d5f0-45ee-a468-789d82332db2
      value_template: >-
        {{ states('input_boolean.shabbat_mode') }}
      turn_on:
        - service: input_boolean.turn_on
          data:
            entity_id: input_boolean.shabbat_mode
      #   - service: switch.turn_on
      #     data:
      #       entity_id: switch.living_room_shabbat_select
      #   - service: switch.turn_on
      #     data:
      #       entity_id: switch.bathroom_shabbat_select
        - service: switch.turn_on
          data:
            entity_id: switch.ensuite_shabbat_select
      turn_off:
      #   - service: input_boolean.turn_off
      #     data:
      #       entity_id: input_boolean.shabbat_mode
      #   - service: switch.turn_off
      #     data:
      #       entity_id: switch.living_room_shabbat_select
      #   - service: switch.turn_off
      #     data:
      #       entity_id: switch.bathroom_shabbat_select
        - service: switch.turn_off
          data:
            entity_id: switch.ensuite_shabbat_select
      icon_template: >-
        {% if is_state('switch.shabbat_mode', 'on') %}
          mdi:motion-sensor-off
        {% else %}
          mdi:motion-sensor
        {% endif %}
