---

substitutions:
  devicename: "unknown-multisensor"
  upper_devicename: "Unknown Room"
  template_id: "unknown_id"

esphome:
  name: "${devicename}"

esp8266:
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  ap:
    ssid: "${upper_devicename}_fallback_hotspot"
    password: !secret ap_passwd

captive_portal:
logger:
api:
ota:
  platform: esphome

i2c:
  sda: D2
  scl: D1
  scan: True
  frequency: 400kHz

binary_sensor:
  - platform: gpio
    pin:
      number: D6
      mode: INPUT_PULLUP
    name: "${upper_devicename} Motion"
    device_class: motion
    filters:
      - delayed_on: 1s
      - delayed_off: 30s
  - platform: status
    name: "${upper_devicename}"

sensor:
  - platform: bme280_i2c
    temperature:
      name: "${upper_devicename} Temperature"
      id: ${template_id}_temperature
      oversampling: 16x
    pressure:
      name: "${upper_devicename} Pressure"
    humidity:
      name: "${upper_devicename} Humidity"
      id: ${template_id}_humidity
    address: 0x76
    update_interval: 60s

  - platform: bh1750
    name: "${upper_devicename} Illuminance"
    id: ${template_id}_illuminance
    address: 0x23
    update_interval: 60s

  - platform: template
    name: "${upper_devicename} Percieved Brightness"
    id: ${template_id}_percieved_brightness
    unit_of_measurement: "%"
    state_class: measurement
    lambda: |-
      if ((id(${template_id}_illuminance).state) > 0.1) {
        return ((log10(id(${template_id}_illuminance).state) / 5) * 100);
      } else {
        return 0;
      }

button:
  - platform: restart
    name: "Restart ${upper_devicename}"
