###
# Light switches
###

- platform: template
  switches:
    night_light_override:
      unique_id: 4e9a2793-1a7b-4b16-aa84-1958b6264791
      friendly_name: "Night Light Override"
      value_template: >-
        {{ states('input_boolean.night_light_override') }}
      turn_on:
        service: input_boolean.turn_on
        data:
          entity_id: input_boolean.night_light_override
      turn_off:
        service: input_boolean.turn_off
        data:
          entity_id: input_boolean.night_light_override
      icon_template: >-
        {% if is_state('switch.night_light_override', 'on') %}
          mdi:shield
        {% else %}
          mdi:shield-off
        {% endif %}
