###
# AC power calculations
###

- platform: template
  sensors:
    living_room_ac_power_consumption:
      friendly_name: "Living room AC power consumption"
      unit_of_measurement: 'kW'
      value_template: >-
        {% if is_state('binary_sensor.living_room_ac_is_on', 'on') and
              is_state('climate.slvn', 'heat_cool') %}
          2.04
        {% elif is_state('binary_sensor.living_room_ac_is_on', 'on') and
              is_state('climate.slvn', 'cool') %}
          2.04
        {% elif is_state('binary_sensor.living_room_ac_is_on', 'on') and
                is_state('climate.slvn', 'heat') %}
          2.317
        {% else %}
          0
        {% endif %}
      icon_template: mdi:flash
    master_bedroom_ac_power_consumption:
      friendly_name: "Master Bedroom AC power consumption"
      unit_of_measurement: 'kW'
      value_template: >-
        {% if is_state('binary_sensor.master_bedroom_ac_is_on', 'on') %}
          0.8
        {% else %}
          0
        {% endif %}
      icon_template: mdi:flash
    total_ac_power_consumption:
      friendly_name: "Total AC power consumption"
      unit_of_measurement: 'kW'
      value_template: >-
        {{
          (states('sensor.living_room_ac_power_consumption') | float)
          +
          (states('sensor.master_bedroom_ac_power_consumption') | float)
        }}
      icon_template: mdi:flash
