###
# TOD
###

- platform: template
  sensors:
    tod_day:
      value_template: >-
        {% if is_state('binary_sensor.day', 'on') %}
          1
        {% else %}
          0
        {% endif %}
