---

exclude:
  entities:
    - binary_sensor.day
    - binary_sensor.night
    - sensor.watchman_last_updated
    - remote.tv
    - automation.count_home_assistant_log_entries
    - binary_sensor.yuval_interactive
    - sensor.date
    - sensor.time
    - sensor.date_time
  entity_globs:
    - sensor.openweathermap_*
    - sensor.jewish_calendar_*
    - sensor.count_*
    - sensor.*_formatted
    - media_player.tv*
  domains:
    - script
    - sun
