---

- alias: "Yuval has left work"
  description: "Notify at home that Yuval has left work, and arrive in x minutes"
  trigger:
    platform: state
    entity_id: person.yuval
    from: 'Yuval work'
    to: 'away'
  condition: "{{ is_state('person.tohar', 'home') }}"
  action:
    service: notify.nest_mini
    data:
      message: "יובל יצא מהעבודה, הוא יגיע בעוד כ {{ states('sensor.yuval_from_work_to_home') }} דקות"
