###
# Play Radio on chromecast
# https://github.com/eyalcha/home-assistant-cookbook/blob/master/chromecast_radio_player_card/README.md
###

play_radio_stream:
  alias: "Play radio stream"
  sequence:
    - service: media_player.play_media
      data_template:
        entity_id: media_player.googlehome3668
        media_content_id: >-
          {% if content_id == "GLGLZ" %}
            https://glzwizzlv.bynetcdn.com/glglz_mp3?awCollectionId=misc&awEpisodeId=glglz
          {% elif content_id == "Galei Zahal" %}
            http://glzwizzlv.bynetcdn.com/glz_mp3?awCollectionId=misc&awEpisodeId=glz
          {% endif %}
        media_content_type: audio/mp3
