---

- alias: "Lights - Turn off when away"
  id: c4219e30-3edb-4e1d-9621-eba64f593883
  trigger:
    platform: state
    entity_id: group.person
    to: 'not_home'
  condition:
    - "{{ is_state('input_boolean.guest_mode', 'off') }}"
    - "{{ is_state('binary_sensor.jewish_calendar_issur_melacha_in_effect', 'off') }}"
  action:
    service: light.turn_off
    data:
      entity_id: light.all_lights
