---

- alias: "Lights - Turn on light when motion is detected at night"
  id: bbe9c72e-6578-4fd1-b25c-12908145ac14
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'on'
  condition:
    - "{{ is_state('binary_sensor.night', 'on') }}"
    - "{{ is_state('light.yeelight_color_living_room_2', 'off') }}"
  action:
    service: light.turn_on
    data:
      entity_id: light.yeelight_color_living_room_2
      kelvin: 3600
      brightness_pct: 2

- alias: "Lights - Turn off the light"
  id: 2c73b4e0-34cc-4cfd-984e-159f321faa64
  mode: restart
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion
    to: 'off'
  condition:
    - "{{ is_state('binary_sensor.night', 'on') }}"
    - "{{ is_state('input_boolean.night_light_override', 'off') }}"
  action:
    - service: timer.start
      data:
        entity_id: timer.motion_lights_night
    - wait_for_trigger:
        platform: event
        event_type: timer.finished
        event_data:
          entity_id: timer.motion_lights_night
    - service: light.turn_off
      data:
        entity_id: light.yeelight_color_living_room_2
        transition: 30

- alias: "Lights - Reset night light override"
  id: 1a225ce8-4fdd-4036-a8cc-ead0639719fc
  trigger:
    platform: state
    entity_id: input_boolean.night_light_override
    to: 'on'
    for:
      hours: 1
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.night_light_override
