---

substitutions:
  name: "pc"
  friendly_name: "PC"
  room: "Office" # Assuming Office, change as needed
  relay_restore_mode: RESTORE_DEFAULT_OFF

packages:
  device_base: !include templates/.athom_plug_base.yaml

wifi:
  use_address: pc-9cd97f.local
