---

substitutions:
  name: "shabbat-plate"
  friendly_name: "Shabbat Plate"
  room: "Dining"
  relay_restore_mode: RESTORE_DEFAULT_ON
  wifi_fast_connect: "true"

packages:
  device_base: !include templates/.athom_plug_base.yaml

# Override the wifi settings from the base package to add static IP
wifi:
  manual_ip:
    static_ip: 10.0.0.40
    gateway: 10.0.0.1
    subnet: 255.255.0.0
  use_address: shabbat-plate-dd5818.local
