---

substitutions:
  name: "spa"
  friendly_name: "Spa"
  room: "Shed"
  relay_restore_mode: RESTORE_DEFAULT_ON
  wifi_fast_connect: "true"

packages:
  device_base: !include templates/.athom_plug_base.yaml

wifi:
  use_address: spa-9cd951-9cd951.local
